server:
  # 启动端口
  port: 9090

spring:
  # 数据库配置
  datasource:
    username: root
    password: root2021
    url: jdbc:mysql://127.0.0.1:3306/ony?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai

# 日志配置
logging:
  level:
    com.ony: debug
    com.github.houbb.resubmit: warn