server:
  # 启动端口
  port: 9090

spring:
  # 数据库配置
  datasource:
    username: root
    password: root2021
    url: jdbc:mysql://127.0.0.1:3306/ony?autoReconnect=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# 日志配置
logging:
  level:
    com.ony: debug
    com.github.houbb.resubmit: warn