spring:
  # 应用名称
  application:
    name: tumo-boot

  # 默认执行的配置文件
  profiles:
    active: dev

  # 数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  # xml mapper 路径
  mapper-locations: classpath:mapper/**/*.xml